# Licenses Reference Data
LICENSE_DETAILS = {
    "License 21": {"products": "Cereal, Sliced Bread, Flour, Oil, Pasta, Sugar Powdered", "level": 0, "cost": 0},
    "License 22": {"products": "Bottled Water, Cheese, Coffee Dark Roast, Eggs - 8 Pack, Milk, Tea Black", "level": 3, "cost": 200},
    "License 23": {"products": "Peanut Butter, Flour, Olive Oil, Pasta Spaghetti, Rice Basmati, Salt", "level": 6, "cost": 400},
    "License 24": {"products": "Orange Juice, Soda, Soda, Apple Juice, Milk - 6 Pack, Soda", "level": 9, "cost": 550},
    "License 25": {"products": "Cake, Cake, Candy, Cereal, Chocolate Bar, Yoghurt", "level": 9, "cost": 550},
    "License 26": {"products": "Bleach, Cleaner, Dishwasher Tablet, Hand Soap, Shampoo, Toiletpaper", "level": 12, "cost": 750},
    "License 48": {"products": "Apple, Tomato, Carrot, Garlic, Kiwi, Lemon, Mango, Mushroom", "level": 12, "cost": 750},
    "License 27": {"products": "Cheese Mozarella, Cheese Parmesan, Honey, Tuna, Eggs-4 Pack, Sugar Powdered", "level": 12, "cost": 750},
    "License 28": {"products": "Butter, Cereal, Chicken, French Fries, Pizza Mixed, Potato Bag", "level": 13, "cost": 1100},
    "License 29": {"products": "Cheese, Coffee Light Roast, Bottled Water, Eggs-12 Pack, Pasta Elbows, Sugar Brown, Tea Green", "level": 16, "cost": 1950},
    "License 30": {"products": "Moussaka, Salmon, Scallop Gratin, Steak, Sushi Large, Sushi Small, Veal Chop", "level": 16, "cost": 1950},
    "License 31": {"products": "Crab Stick, Hot Sauce, Icecream Chocolate, Ketchup, Mayonnaise, Pizza Cheddar", "level": 20, "cost": 2800},
    "License 49": {"products": "Melon, Onion, Pear, Pineapple, Potato, Squash, Zucchini, Watermelon, Artichoke", "level": 25, "cost": 3000},
    "License 32": {"products": "Beer Blonde Ale - 6 PACK, Beer Blonde Ale - Keg, Beer Blonde Ale, Beer Lager, Chips, Houmus, Vodka", "level": 30, "cost": 3500},
    "License 33": {"products": "Chips, Flour, Mashed Potatoes, Pepper, Rice, Sandwich Bread, Sugar Powdered", "level": 30, "cost": 3500},
    "License 34": {"products": "Bleach, Cleaner, Dishwasher Tablet, Cleaner, Dish Soap Durian, Toiletpaper", "level": 42, "cost": 5000},
    "License 35": {"products": "Galette Ham&Cheese, Ground Beef, Ham Pastry, Ham, Lasagne, Proscuito, Chicken Leg", "level": 42, "cost": 5000},
    "License 36": {"products": "Coffee Medium Roast, Soda, Soda, Soda, Soda, Sugar Light Brown", "level": 42, "cost": 5000},
    "License 37": {"products": "Green Beans, Icecream Vanilla, Icecream, Pizza, Potato Pops, Veggie Mix", "level": 56, "cost": 9500},
    "License 38": {"products": "Beer Blonde Ale, Beer Lager - 6 PACK, Beer Lager - Keg, Vodka, Whiskey, Wine", "level": 56, "cost": 9500},
    "License 39": {"products": "Cheese Parmesan, Cheese, Clotted Cream, Pasta Penne, Rice, Sugar Cane, Yoghurt", "level": 56, "cost": 9500},
    "License 50": {"products": "Avocado, Banana, Grapefruit, Pumpkin, Papaya, Clementine", "level": 63, "cost": 12000},
    "License 40": {"products": "Cleaner, Dishwasher Tablet, Dish Soap Lemon, Fabric Softener", "level": 70, "cost": 16000},
    "License 41": {"products": "Book, Book, Book, Book, Book, Book", "level": 70, "cost": 16000},
    "License 42": {"products": "Cleaner, Cat Food, Cat Food, Dog Food", "level": 70, "cost": 16000},
    "License 43": {"products": "Cake, Cake, Chips, Chocolate Spread, Soda Can - 6 Pack, Soda Can - 6 Pack, Bottled Water", "level": 81, "cost": 22000},
    "License 44": {"products": "Fabric Softener, Paper Towel, Toiletpaper, Toothpaste", "level": 81, "cost": 22000},
    "License 45": {"products": "Book, Book, Book, Book, Book, Book", "level": 81, "cost": 22000},
    "License 46": {"products": "Cake, Cake, Chocolate Bar, Chocolate Powder, Sugar, Yoghurt", "level": 81, "cost": 22000},
    "License 47": {"products": "Beer Blonde Ale - 6 PACK, Beer Blonde Ale - Keg, Whiskey, Whisky, Wine, Wine", "level": 90, "cost": 30000},
    "License 69": {"products": "Vanilla Flavour, Chocolate Flavour, Strawberry Flavour, Lemon Flavour, Blue Moon Flavour, Forest Fruit Flavour, Cone A, Cone B, Cone C", "level": 6, "cost": 2000},
    "License 51": {"products": "Women High Heels, Basic Tank Top, Hoodie, Training Shoes, Hat, Flip-flops, Leather Belt", "level": 6, "cost": 2000},
    "License 52": {"products": "Men’s Cotton T-Shirt, Crew Socks, Lounge Pants, Men’s Boxer Briefs, Classic Men's Shoe, Women's Cotton Underwear", "level": 6, "cost": 2000},
    "License 53": {"products": "Women's shoes, Raincoat, Shorts, Trousers, Women's V-Neck Tee, Men's Sports Shoe", "level": 6, "cost": 2000},
    "License 54": {"products": "Emergency Led, Emergency Led Soft, Powerbank, Lightning Charging Cable, USB-C Charging Cable, Wall Adapter", "level": 6, "cost": 2000},
    "License 55": {"products": "Flashlight, Battery 6X, Phone, Fast Car Charger, HDMI Cable, Walkie-Talkie", "level": 6, "cost": 2000},
    "License 56": {"products": "Headphones, Flash Drive, Keyboard, Electric Toothbrush, Video Doorbell, Wireless Mouse, Bluetooth Speaker", "level": 6, "cost": 2000},
    "License 57": {"products": "Hammer Multitool, Multiscrewdriver, Tape Measure, Precision Nail Kit", "level": 6, "cost": 2000},
    "License 58": {"products": "Glue Gun, Wall Hook, Cable Clips, Superglue, Mounting Tape", "level": 6, "cost": 2000},
    "License 59": {"products": "Nose Pliers, Level Set, Portable Toolbox, Screwdriver Set, Hex Key Set", "level": 6, "cost": 2000},
    "License 60": {"products": "Baby Lotion, Baby Oil, Baby Powder, Baby Shampoo, Baby Diapers, Baby Wipes, Pacifier", "level": 6, "cost": 2000},
    "License 61": {"products": "Packed Baby Food, Banana Puree, Strawberry Puree, Vegetable Puree, Baby Bottle", "level": 6, "cost": 2000},
    "License 62": {"products": "Canned Green Beans, Canned Cayenne Pepper, Canned Crushed Pineapple, Canned Beans, Canned Mixed Fruit", "level": 6, "cost": 2000},
    "License 63": {"products": "Canned Peaches, Canned Tuna, Canned Tomatoes, Canned Tuna, Canned Corn", "level": 6, "cost": 2000},
    "License 64": {"products": "Aluminum Foil, Chopping Board, Cutlery Set, Dish Sponge, Garbage Bags", "level": 6, "cost": 2000},
    "License 65": {"products": "Grater, Kitchen Knife, Plastic Cups, Stretch Film, Vegetable Peeler", "level": 6, "cost": 2000},
    "License 66": {"products": "Bagel Frozen, Bagel, Bread Frozen, Bread, Croissant Frozen, Croissant, Donut Frozen, Donut, Muffin Frozen, Muffin", "level": 1, "cost": 2000},
    "License 67": {"products": "Baguette Frozen, Baguette, Cinnamon Swirl Frozen, Cinnamon Swirl, Puff Pastry Twists Frozen, Puff Pastry Twists, Cookie Frozen, Cookie, Dinner Rolls Frozen, Dinner Rolls", "level": 1, "cost": 2000},
    "License 68": {"products": "Empanada Frozen, Empanada, Focaccia Frozen, Focaccia, Obi-Non Frozen, Obi-Non, Pastel de Nata Frozen, Pastel de Nata, Pretzel Frozen, Pretzel", "level": 1, "cost": 2000},
}