<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <Version>0.3.2</Version>
    <FileVersion>0.3.2</FileVersion>
    <AssemblyVersion>0.3.2.0</AssemblyVersion>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <ReferenceDirectory>$(MSBuildProjectDirectory)\lib</ReferenceDirectory>

    <GamePluginsFolder>C:\Program Files (x86)\Steam\steamapps\common\Supermarket Simulator\BepInEx\plugins</GamePluginsFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony" Private="false">
      <HintPath>$(ReferenceDirectory)\0Harmony.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp" Private="false">
      <HintPath>$(ReferenceDirectory)\Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="BepInEx.Core" Private="false">
      <HintPath>$(ReferenceDirectory)\BepInEx.Core.dll</HintPath>
    </Reference>

    <Reference Include="BepInEx.Unity.IL2CPP" Private="false">
      <HintPath>$(ReferenceDirectory)\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>

    <Reference Include="Il2CppInterop.Runtime" Private="false">
      <HintPath>$(ReferenceDirectory)\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>

    <Reference Include="Il2Cppmscorlib" Private="false">
      <HintPath>$(ReferenceDirectory)\Il2Cppmscorlib.dll</HintPath>
    </Reference>

    <Reference Include="PhotonUnityNetworking" Private="false">
      <HintPath>$(ReferenceDirectory)\PhotonUnityNetworking.dll</HintPath>
    </Reference>

    <Reference Include="Unity.Localization" Private="false">
      <HintPath>$(ReferenceDirectory)\Unity.Localization.dll</HintPath>
    </Reference>

    <Reference Include="Unity.TextMeshPro" Private="false">
      <HintPath>$(ReferenceDirectory)\Unity.TextMeshPro.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule" Private="false">
      <HintPath>$(ReferenceDirectory)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.IMGUIModule" Private="false">
      <HintPath>$(ReferenceDirectory)\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.InputLegacyModule" Private="false">
      <HintPath>$(ReferenceDirectory)\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.TextRenderingModule" Private="false">
      <HintPath>$(ReferenceDirectory)\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.UI" Private="false">
      <HintPath>$(ReferenceDirectory)\UnityEngine.UI.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.UIElementsModule" Private="false">
      <HintPath>$(ReferenceDirectory)\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.UIModule" Private="false">
      <HintPath>$(ReferenceDirectory)\UnityEngine.UIModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target
    Name="CopyToGamePlugins"
    AfterTargets="Build"
    Condition="'$(GITHUB_ACTIONS)' != 'true' And Exists('$(GamePluginsFolder)')">

    <Message
      Importance="high"
      Text="Copying mod and dependencies to $(GamePluginsFolder)..." />

    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFolder="$(GamePluginsFolder)"
      SkipUnchangedFiles="true" />

    <Copy
      SourceFiles="@(ReferenceCopyLocalPaths)"
      DestinationFolder="$(GamePluginsFolder)"
      Condition="'%(Filename)' == 'Archipelago.MultiClient.Net' Or '%(Filename)' == 'Newtonsoft.Json'"
      SkipUnchangedFiles="true" />
  </Target>

</Project>